#!/bin/sh -e

# create the log directory if it doesn't exist
[ -d /var/log/gomicro/mist ] || mkdir -p /var/log/gomicro/mist

# tell svlogd to drop the stdout into our custom location
cd /var/log/gomicro/mist
exec svlogd -v -ttt /var/log/gomicro/mist
