#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gomicro/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

local_mist_md5 = execute "local mist md5" do
  command "cat /var/microbox/mist.md5"
  not_if { ! ::File.exists? "/var/microbox/mist.md5" }
end

aws_mist_md5 = execute "aws mist md5" do
  command "curl \
    -f \
    -k \
    https://s3.amazonaws.com/tools.microbox.cloud/mist/linux/amd64/mist.md5 \
      | tee /tmp/mist.md5"
end

if local_mist_md5 != aws_mist_md5
  # Stop mist
  service 'mist' do
    action :disable
    not_if { !Dir.exist?('/etc/service/mist') }
  end

  execute "Download mist" do
    command "curl \
      -f \
      -k \
      -o /usr/local/bin/mist \
      https://s3.amazonaws.com/tools.microbox.cloud/mist/linux/amd64/mist"
  end

  execute "Chmod mist" do
    command "chmod 755 /usr/local/bin/mist"
  end

  service 'mist' do
    action :enable
    not_if { !Dir.exist?('/etc/service/mist') }
  end

  execute "Finalize update" do
    command "mv /tmp/mist.md5 /var/microbox/mist.md5"
  end
end

local_hooks_md5 = execute "local hooks md5" do
  command "cat /var/microbox/hooks.md5"
  not_if { ! ::File.exists? "/var/microbox/hooks.md5" }
end

aws_hooks_md5 = execute "aws hooks md5" do
  command "curl \
    -f \
    -k \
    https://s3.amazonaws.com/tools.microbox.cloud/hooks/mist-stable.md5 \
      | tee /tmp/hooks.md5"
end

if local_hooks_md5 != aws_hooks_md5
  execute "update hooks" do
    command "curl \
      -f \
      -k \
      https://s3.amazonaws.com/tools.microbox.cloud/hooks/mist-stable.tgz \
        | tar -xz -C /opt/microbox/hooks"
  end

  execute "Finalize update" do
    command "mv /tmp/hooks.md5 /var/microbox/hooks.md5"
  end
end
