#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

local_mist_md5 = execute "local mist md5" do
  command "cat /var/nanobox/mist.md5"
  not_if { ! ::File.exists? "/var/nanobox/mist.md5" }
end

aws_mist_md5 = execute "aws mist md5" do
  command <<-END
    bash -c 'curl \
      -f \
      -k \
      https://d3ep67zochz54j.cloudfront.net/mist/linux/amd64/mist.md5 \
        | tee /tmp/mist.md5'
  END
end

if local_mist_md5 != aws_mist_md5
  # Stop mist
  service 'mist' do
    action :disable
    not_if { !Dir.exist?('/etc/service/mist') }
  end

  execute "Download mist" do
    command <<-END
      bash -c 'curl \
        -f \
        -k \
        -o /usr/local/bin/mist \
        https://d3ep67zochz54j.cloudfront.net/mist/linux/amd64/mist'
    END
  end

  execute "Chmod mist" do
    command <<-END
      bash -c 'chmod 755 /usr/local/bin/mist'
    END
  end

  service 'mist' do
    action :enable
    not_if { !Dir.exist?('/etc/service/mist') }
  end

  execute "Finalize update" do
    command <<-END
      bash -c 'mv /tmp/mist.md5 /var/nanobox/mist.md5'
    END
  end
end

local_hooks_md5 = execute "local hooks md5" do
  command "cat /var/nanobox/hooks.md5"
  not_if { ! ::File.exists? "/var/nanobox/hooks.md5" }
end

aws_hooks_md5 = execute "aws hooks md5" do
  command <<-END
    bash -c 'curl \
      -f \
      -k \
      https://d1ormdui8qdvue.cloudfront.net/hooks/mist-stable.md5 \
        | tee /var/nanobox/hooks.md5'
  END
end

if local_hooks_md5 != aws_hooks_md5
  execute "update hooks" do
    command <<-END
      bash -c 'curl \
          -f \
          -k \
          https://d1ormdui8qdvue.cloudfront.net/hooks/mist-stable.tgz \
            | tar -xz -C /opt/nanobox/hooks'
    END
  end
end
